name: Update Markdown Dates
on:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:

jobs:
  update-dates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          
      - name: Install dependencies
        run: pip install requests
          
      # Modified step to handle exit code 1
      - name: Run date updater
        id: updater
        run: |
          python scripts/update-date.py || true
          # Check if any files were modified
          if git diff --quiet --exit-code -- content/; then
            echo "changes_made=false" >> $GITHUB_OUTPUT
          else
            echo "changes_made=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push changes
        if: steps.updater.outputs.changes_made == 'true'
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add content/
          git commit -m "Auto-update content dates from repo activity [skip ci]"
          git push

      - name: Trigger Hugo build
        if: steps.updater.outputs.changes_made == 'true'
        uses: actions/github-script@v6
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'hugo.yaml',
              ref: context.ref,
            })