name: Update Markdown Dates
on:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:

jobs:
  update-dates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          
      - name: Install dependencies
        run: pip install requests
          
      - name: Run date updater
        run: python scripts/update-date.py
        env:
          GITHUB_EVENT_NAME: ${{ github.event_name }}
        
      - name: Commit and push changes
        if: success()
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add content/
          git diff --cached --quiet || {
            git commit -m "Auto-update content dates from repo activity [skip ci]"
            git push
          }